### ISSUE TITLE
Test dataset public link not working?

### ISSUE THREAD

**Issue by deqiankong** [EGO4D/social-interactions#11]
Hello,

I was trying to download test set of TTM from CLI or S3, but I got permission denied from both requests.

I tried "ego4d --dataset social_test", but got " An error occurred (403) when calling the HeadObject operation: Forbidden".

Also I tested "aws s3 s3://ego4d-consortium-sharing/public/v1/social_test/ ./", it says "fatal error: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied".

Could you please help me check with that?

Thank you.

**Comment by zcxu-eric** [comment]
Hi, please follow the instructions here: https://ego4d-data.org/docs/start-here/ . Please check the configuration of aws CLI if you got such error.
