### ISSUE TITLE
Error occurred when I ran "python scripts/download_clips.py"

### ISSUE THREAD

**Issue by koubun-ko-df** [EGO4D/social-interactions#12]
Hi, an error occurred when downloading videos, could you tell me how to fix it? Thank you!
![image](https://user-images.githubusercontent.com/54608650/181150457-f98d7636-826a-4963-a587-7986658204e1.png)

**Comment by geanrobotics** [comment]
Hello, I'm having the same issue here - what was the solution? I downloaded the data using  `ego4d --output_directory="./" --benchmarks=AV --dataset annotations --aws_profile_name ego4d ` and reorganised it as described in the README. When I run, python scripts/download_clips.py - I get the same error as above.
