### ISSUE TITLE
Error occurred when I ran "python scripts/download_clips.py"

### ISSUE THREAD

**Issue by koubun-ko-df** [EGO4D/social-interactions#13]
Hi, an error occurred when downloading videos, could you tell me how to fix it? Thank you!
![image](https://user-images.githubusercontent.com/54608650/181193358-9bd93d36-2044-404b-8eb5-a19c36fa8c65.png)

**Comment by koubun-ko-df** [comment]
I changed the variables "parent_*" to "video_*", but another error occurred:
![image](https://user-images.githubusercontent.com/54608650/181225358-45ca189b-dc24-405d-bd34-b92dfaf173ef.png)

**Comment by zephyrzhu1998** [comment]
> I changed the variables "parent__" to "video__", but another error occurred: ![image](https://user-images.githubusercontent.com/54608650/181225358-45ca189b-dc24-405d-bd34-b92dfaf173ef.png)

Hi Huhaowen,
Yes, you need to change the variables "parent__" to "video__", we will also update this. Then the script is right. The error in your screenshot says "aws: not found". Maybe you can check if you installed aws successfully.
