### ISSUE TITLE
Cannot find av_test__unannotated.json

### ISSUE THREAD

**Issue by VictoriaHY** [EGO4D/social-interactions#3]
Hi, I followed the instruction to download annotation. But ego4d annotations only contains av_train.json and av_val.json.
Do you have any ideas about where av_test__unannotated.json is?

Thank you!

**Comment by EGO4D** [comment]
The test annotations are not yet available.  They will be available in the coming few days.  We'll update here when they do.

**Comment by zcxu-eric** [comment]
Hello,
To avoid jeopardizing other benchmarks, our av_test_unannotated.json cannot contain any gt info. Our current solution is to crop the gt images and audio segments. You may find them through the latest instructions in README files.
