### ISSUE TITLE
Something about the submit of test_data results on EvalAi

### ISSUE THREAD

**Issue by lemon-prog123** [EGO4D/social-interactions#7]
Hi I have read the submit guideline on Eval Ai. But it seems that the submit guideline is not completive. What should I really record in [results] of the JSON file? Or what format should I use in the JSON file.

**Comment by zephyrzhu1998** [comment]
@lemon-prog123 Hi, there is something wrong with the guideline. Sorry for that and we will fix it later. The format should be like this:
{
            "version": "1.0",
            "challenge": "ego4d_looking_at_me",
            "results":[
                        {
                            "video_id": video id,
                            "unique_id": unique id for each frame,
                            "track_id": track id,
                            "label": predict label,
                            "score": score
                        },
                        ...
                        {
                            "video_id": video id,
                            "unique_id": unique id for each frame,
                            "track_id": track id,
                            "label": predict label,
                            "score": score
                        },
                ],
        }

**Comment by lemon-prog123** [comment]
> @lemon-prog123 Hi, there is something wrong with the guideline. Sorry for that and we will fix it later. The format should be like this: { "version": "1.0", "challenge": "ego4d_looking_at_me", "results":[ { "video_id": video id, "unique_id": unique id for each frame, "track_id": track id, "label": predict label, "score": score }, ... { "video_id": video id, "unique_id": unique id for each frame, "track_id": track id, "label": predict label, "score": score }, ], }

Thank you for your answer! And I also want to know that whether the test phase on Eval Ai will be the final dataset used for competition. Or we will have another dataset for this competition.

**Comment by zephyrzhu1998** [comment]
> > @lemon-prog123 Hi, there is something wrong with the guideline. Sorry for that and we will fix it later. The format should be like this: { "version": "1.0", "challenge": "ego4d_looking_at_me", "results":[ { "video_id": video id, "unique_id": unique id for each frame, "track_id": track id, "label": predict label, "score": score }, ... { "video_id": video id, "unique_id": unique id for each frame, "track_id": track id, "label": predict label, "score": score }, ], }
> 
> Thank you for your answer! And I also want to know that whether the test phase on Eval Ai will be the final dataset used for competition. Or we will have another dataset for this competition.

Yes, it will be the final dataset used for the competition.

**Comment by lemon-prog123** [comment]
> > > @lemon-prog123 Hi, there is something wrong with the guideline. Sorry for that and we will fix it later. The format should be like this: { "version": "1.0", "challenge": "ego4d_looking_at_me", "results":[ { "video_id": video id, "unique_id": unique id for each frame, "track_id": track id, "label": predict label, "score": score }, ... { "video_id": video id, "unique_id": unique id for each frame, "track_id": track id, "label": predict label, "score": score }, ], }
> > 
> > 
> > Thank you for your answer! And I also want to know that whether the test phase on Eval Ai will be the final dataset used for competition. Or we will have another dataset for this competition.
> 
> Yes, it will be the final dataset used for the competition.

Thanks a lot. And I have uploaded a Json file follow the format above. But it seems that something wrong with it. I have read the stderr as follows: "ValueError: Groundtruth and predictions CSV must have the same number of unique rows." . Could you please tell me how many results should it contains in predictions?

**Comment by lemon-prog123** [comment]
> > > > @lemon-prog123 Hi, there is something wrong with the guideline. Sorry for that and we will fix it later. The format should be like this: { "version": "1.0", "challenge": "ego4d_looking_at_me", "results":[ { "video_id": video id, "unique_id": unique id for each frame, "track_id": track id, "label": predict label, "score": score }, ... { "video_id": video id, "unique_id": unique id for each frame, "track_id": track id, "label": predict label, "score": score }, ], }
> > > 
> > > 
> > > Thank you for your answer! And I also want to know that whether the test phase on Eval Ai will be the final dataset used for competition. Or we will have another dataset for this competition.
> > 
> > 
> > Yes, it will be the final dataset used for the competition.
> 
> Thanks a lot. And I have uploaded a Json file follow the format above. But it seems that something wrong with it. I have read the stderr as follows: "ValueError: Groundtruth and predictions CSV must have the same number of unique rows." . Could you please tell me how many results should it contains in predictions?

By the way,I have 2063259 rows in my "results".

**Comment by zephyrzhu1998** [comment]
@lemon-prog123 It equals to the number of frames in test set.

**Comment by lemon-prog123** [comment]
> 

I have checked it out and there are exactly 2063259 pictures in videos_challenge. I have unzip the orignal_file again and ensure that there are 2063259 pictures in the test set.  Is that right for the number of test set?

**Comment by lemon-prog123** [comment]
> 

ok I have checked it out. Thank you !
