### ISSUE TITLE
Which stride did the baseline choose?

### ISSUE THREAD

**Issue by lemon-prog123** [EGO4D/social-interactions#8]
Hi! I am puzzled about which stride was used in the baseline and gaze360 model's training. I have read the paper and the answer is 3. But the config in common shows that the default stride is 13.

**Comment by lemon-prog123** [comment]
And for another ,  you have provided us with checkpoints including lam-best and gaze360-lam-best.  But it seems that gaze360-lam-best is the version that had been fine-tuned in lam task yet. Can I get a version of orginal gaze360 checkpoint which you use in training process? That is the version that haven't been fine-tuned yet.
Thank you a lot!

**Comment by zcxu-eric** [comment]
During training, we used a stride of 3, the default value was only used for debug. 

You can find the pretrained checkpoint of gaze360 [here](http://gaze360.csail.mit.edu/files/gaze360_model.pth.tar).

**Comment by lemon-prog123** [comment]
> 

Thanks a lot!

**Comment by htahboub** [comment]
Hi @zcxu-eric, I know this is a bit old now, but I just wanted to clarify: for the validation results that you report, I assume you use a stride of 1. Is that right?
