### ISSUE TITLE
Looking at Me Test Dataset Scores

### ISSUE THREAD

**Issue by fpusch** [EGO4D/social-interactions#9]
Training a model on the LAM train dataset prints evaluation inference results on the validation dataset like
```
mAP: 0.789340
TOP-1 Acc:92.725%
        LAM     NLAM
LAM     58.120  41.880
NLAM    3.815   96.185
mAP: 0.7893 best mAP: 0.7893
```
Running the actual tests against the test dataset (social_test) only returns a pred.csv but no further scores. Is this intentional? Specifically I am wondering because in my case using the reference gaze360 model results in a pred.csv with every line being score at `<0.5` which I'd interpret as it as always predicting NLAM. This would not be consistent with the results shown in the paper. Am I missing something here?

I have seen #3 and the explanation that producing a gt.csv would compromise the other challenges. However without it, interpreting the applicability of the results onto the test dataset seems very difficult.

On a side note: the submission format linked from the README currently leads to a 404 page.

Thanks for any help :)

**Comment by zcxu-eric** [comment]
Hi fpusch,

For testset, we cannot release the gt labels, that are credential in this challenge. If you want to get the score for testset predictions, please submit it to the Looking-at-me challenge. The gaze360 is only used to initialize the backbone of our model, if you directly use it for testing, it will only output a constant score.

The submission guideline link has been updated.

**Comment by koubun-ko-df** [comment]
> Hi fpusch,
> 
> For testset, we cannot release the gt labels, that are credential in this challenge. If you want to get the score for testset predictions, please submit it to the Looking-at-me challenge. The gaze360 is only used to initialize the backbone of our model, if you directly use it for testing, it will only output a constant score.
> 
> The submission guideline link has been updated.

Hi, it seems that the submission guideline link here is 404 again, could you help with that? Thank you!
![image](https://user-images.githubusercontent.com/54608650/183230506-a7935989-2437-4e78-a8fd-8eb0c87939e9.png)

**Comment by zcxu-eric** [comment]
Hello, the EvalAI platform may change the pointers occasionally. We have updated the link. Next time if you happen to find the link not accessible, you could search our challenge directly on EvalAI. Thanks.

**Comment by koubun-ko-df** [comment]
> Hello, the EvalAI platform may change the pointers occasionally. We have updated the link. Next time if you happen to find the link not accessible, you could search our challenge directly on EvalAI. Thanks.

Thank you for your immediate reply!
It says the results should be summitted as a json file, is there any standard code to convert pred.csv to json?

**Comment by zephyrzhu1998** [comment]
> > Hello, the EvalAI platform may change the pointers occasionally. We have updated the link. Next time if you happen to find the link not accessible, you could search our challenge directly on EvalAI. Thanks.
> 
> Thank you for your immediate reply! It says the results should be summitted as a json file, is there any standard code to convert pred.csv to json?

Hi Huhaowen,
Sorry, we don't provide this script.

**Comment by koubun-ko-df** [comment]
> 

OK, I understand it. Just to make sure, if the "uid" in the code represents the video id in json?
![image](https://user-images.githubusercontent.com/54608650/183317807-e3536fc5-ba03-40ad-81bb-487544186b75.png)
![image](https://user-images.githubusercontent.com/54608650/183317774-3480bbd9-0071-456f-955b-8024056b46f6.png)

**Comment by zcxu-eric** [comment]
> > 
> 
> OK, I understand it. Just to make sure, if the "uid" in the code represents the video id in json? ![image](https://user-images.githubusercontent.com/54608650/183317807-e3536fc5-ba03-40ad-81bb-487544186b75.png) ![image](https://user-images.githubusercontent.com/54608650/183317774-3480bbd9-0071-456f-955b-8024056b46f6.png)

correct

**Comment by koubun-ko-df** [comment]
> > > 
> > 
> > 
> > OK, I understand it. Just to make sure, if the "uid" in the code represents the video id in json? ![image](https://user-images.githubusercontent.com/54608650/183317807-e3536fc5-ba03-40ad-81bb-487544186b75.png) ![image](https://user-images.githubusercontent.com/54608650/183317774-3480bbd9-0071-456f-955b-8024056b46f6.png)
> 
> correct

Hello Eric, sorry for bothering you again!

I submitted a json file and there occurred an error when calculating the results:
![image](https://user-images.githubusercontent.com/54608650/183401531-51fd3a6c-45e0-47e6-af7d-1413a590d147.png)

There seems something wrong with my json. Could you help check it? Thank you in advance!
![image](https://user-images.githubusercontent.com/54608650/183401772-7e3d4bb6-2418-4a73-8ad6-5c9d9456d96e.png)
![image](https://user-images.githubusercontent.com/54608650/183401845-a859b2d4-ce12-46e2-ae2b-f7c8d8184dbd.png)

**Comment by zcxu-eric** [comment]
> > > > 
> > > 
> > > 
> > > OK, I understand it. Just to make sure, if the "uid" in the code represents the video id in json? ![image](https://user-images.githubusercontent.com/54608650/183317807-e3536fc5-ba03-40ad-81bb-487544186b75.png) ![image](https://user-images.githubusercontent.com/54608650/183317774-3480bbd9-0071-456f-955b-8024056b46f6.png)
> > 
> > 
> > correct
> 
> Hello Eric, sorry for bothering you again!
> 
> I submitted a json file and there occurred an error when calculating the results: ![image](https://user-images.githubusercontent.com/54608650/183401531-51fd3a6c-45e0-47e6-af7d-1413a590d147.png)
> 
> There seems something wrong with my json. Could you help check it? Thank you in advance! ![image](https://user-images.githubusercontent.com/54608650/183401772-7e3d4bb6-2418-4a73-8ad6-5c9d9456d96e.png) ![image](https://user-images.githubusercontent.com/54608650/183401845-a859b2d4-ce12-46e2-ae2b-f7c8d8184dbd.png)

 "label" should always be "1", and "score" denotes the probability for being predicted as "1"

**Comment by koubun-ko-df** [comment]
> "label" should always be "1", and "score" denotes the probability for being predicted as "1"

Hi! Sorry for disturbing you again.

I got a reasonable result (similar to the Ego4D paper) by doing as you said. But when I checked the dataset, I found something weired:
in line 198 of data_loader.py, I saw this message being printed many times. May I ask if it's normal? Does it mean the faces in some frames are not tracked? Thank you!
![image](https://user-images.githubusercontent.com/54608650/184813091-929309b0-b383-409c-8fea-7107a55d1a74.png)

**Comment by zcxu-eric** [comment]
> > "label" should always be "1", and "score" denotes the probability for being predicted as "1"
> 
> Hi! Sorry for disturbing you again.
> 
> I got a reasonable result (similar to the Ego4D paper) by doing as you said. But when I checked the dataset, I found something weired: in line 198 of data_loader.py, I saw this message being printed many times. May I ask if it's normal? Does it mean the faces in some frames are not tracked? Thank you! ![image](https://user-images.githubusercontent.com/54608650/184813091-929309b0-b383-409c-8fea-7107a55d1a74.png)

Yes, some faces are missed due to the sharp motion, detector failure, challenging lighting conditions, etc. You can disable it if it is annoying.

**Comment by koubun-ko-df** [comment]
> > > "label" should always be "1", and "score" denotes the probability for being predicted as "1"
> > 
> > 
> > Hi! Sorry for disturbing you again.
> > I got a reasonable result (similar to the Ego4D paper) by doing as you said. But when I checked the dataset, I found something weired: in line 198 of data_loader.py, I saw this message being printed many times. May I ask if it's normal? Does it mean the faces in some frames are not tracked? Thank you! ![image](https://user-images.githubusercontent.com/54608650/184813091-929309b0-b383-409c-8fea-7107a55d1a74.png)
> 
> Yes, some faces are missed due to the sharp motion, detector failure, challenging lighting conditions, etc. You can disable it if it is annoying.

Got it, thank you for quick response!
